# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FormulariosBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    providers:  
        usuario:
            entity: { class: FormulariosBundle\Entity\Usuario, property: email }
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN'}

    firewalls:
        administrador:
            pattern: ^/admin
            provider: in_memory
            http_basic: ~
        default:
            pattern: ^/
            provider: usuario
            anonymous: ~
            form_login:
               login_path: login
               check_path: login_check
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                target_path_parameter: redirect_url

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

