FormulariosBundle\Entity\Institucion:
  type: entity
  table: institucion
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    cuit:
      type: string
      length: 11
      nullable: true
    nombre:
      type: string
      length: 200
      nullable: false
    domicilio:
      type: string
      length: 100
      nullable: false
    domicilio_legal:
      type: string
      length: 100
      nullable: true
    cp:
      type: string
      length: 10
      nullable: false
    telefono:
      type: string
      length: 40
      nullable: false
    responsable:
      type: string
      length: 100
      nullable: true
    email:
      type: string
      length: 100
      nullable: false
    fecha_constitucion:
      type: date
      nullable: true
    fecha_inicio_actividades:
      type: date
      nullable: true
    facturacion_ultimo_ejercicio:
      type: float
      length: 10
      nullable: true
    representante_nombre:
      type: string
      length: 100
      nullable: true
    representante_cuit:
      type: string
      length: 12
      nullable: true
    representante_domicilio:
      type: string
      length: 100
      nullable: true
    representante_email:
      type: string
      length: 100
      nullable: true
    representante_cargo:
      type: string
      length: 50
      nullable: true
    representante_telefono:
      type: string
      length: 30
      nullable: true
    apoderado_nombre:
      type: string
      length: 100
      nullable: true
    apoderado_cuit:
      type: string
      length: 12
      nullable: true
  manyToOne:
    localidad:
      targetEntity: FormulariosBundle\Entity\Localidad
      inversedBy: institucion
      joinColumns:
        localidad_id:
          referencedColumnName: id      
    domicilio_legal_localidad_id:
      targetEntity: FormulariosBundle\Entity\Localidad
      inversedBy: institucion
      joinColumns:
        domicilio_legal_localidad_id:
          referencedColumnName: id
    tramite:
      targetEntity: FormulariosBundle\Entity\Tramite
      inversedBy: instituciones
      joinColumns:
        tramite_asociado_id:
          referencedColumnName: id
    tramite_presta_servicio:
      targetEntity: FormulariosBundle\Entity\Tramite
      inversedBy: instituciones_prestatarias
      cascade: ["all"]
      joinColumns:
        tramite_id:
          referencedColumnName: id
          onDelete: CASCADE
          onUpdate: CASCADE
    tramite_otras:
      targetEntity: FormulariosBundle\Entity\Localidad
      inversedBy: otras_instituciones
      joinColumns:
        otra_tramite_id:
          referencedColumnName: id
