FormulariosBundle\Entity\Roles:
  type: entity
  table: roles
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    rol:
      type: string
      length: 40
      nullable: false
