FormulariosBundle\Entity\UVT:
  type: entity
  table: uvt
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: 200
      nullable: false
    domicilio:
      type: string
      length: 100
      nullable: false
    localidad:
      type: string
      length: 100
      nullable: false
    telefono:
      type: string
      length: 50
      nullable: false
    fax:
      type: string
      length: 50
      nullable: false
    cp:
      type: string
      length: 10
      nullable: false
    email:
      type: string
      length: 100
      nullable: true
    habilitado:
      type: boolean
      nullable: true
  oneToMany:
    representantes:
      targetEntity: FormulariosBundle\Entity\Representante_UVT
      mappedBy: uvt
