login:
    path:     /
    defaults: { _controller: FormulariosBundle:Login:login }

agregarusuario:
    path:     /nuevoUsuario/
    defaults: { _controller: FormulariosBundle:Login:nuevoUsuario }

portada:
    path:     /tramite/
    defaults: { _controller: FormulariosBundle:Portada:portada }
