login:
    path:     /{_locale}/login
    defaults: { _controller: FormulariosBundle:Login:login }
    requirements:
        _locale: en|es

login_check:
    path:     /login_check

admin:
    path:     /admin/
    defaults: { _controller: FormulariosBundle:Login:admin }

nuevoUsuario:
    path:     /{_locale}/nuevoUsuario/
    defaults: { _controller: FormulariosBundle:Login:nuevoUsuario }
    requirements:
        _locale: en|es

validaUsuario:
    path:     /validaUsuario/
    defaults: { _controller: FormulariosBundle:Login:validate }

portada:
    path:     /tramite/
    defaults: { _controller: FormulariosBundle:Portada:portada }

ANR_Eventos:
    path:     /ANR_Eventos/
    defaults: { _controller: FormulariosBundle:Formularios:ANR_Eventos }


