login:
    path:     /login
    defaults: { _controller: FormulariosBundle:Login:login }

login_check:
    path:     /login_check

admin:
    path:     /admin/
    defaults: { _controller: FormulariosBundle:Login:admin }

nuevoUsuario:
    path:     /nuevoUsuario/
    defaults: { _controller: FormulariosBundle:Login:nuevoUsuario }

validaUsuario:
    path:     /validaUsuario/
    defaults: { _controller: FormulariosBundle:Login:validate }

portada:
    path:     /tramite/
    defaults: { _controller: FormulariosBundle:Portada:portada }

ANR_Eventos:
    path:     /ANR_Eventos/
    defaults: { _controller: FormulariosBundle:Formularios:ANR_Eventos }



