FormulariosBundle\Entity\Usuario:
    properties:
        apellido:
            - NotBlank: ~
            - Type: string
        nombre:
            - NotBlank: ~
            - Type: string
        organizacion:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: El email no es válido.
                checkMX: true
        password:
            - NotBlank: ~
            - Length:
                min: 6
                minMessage: 'La contraseña debe tener un mínimo de {{ limit }} caracteres'
        telefono:
            - NotBlank: ~


